const shell = (title: string, body: string, script = '') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} | PullUp</title><style>
:root{color-scheme:light;--bg:#fff9f2;--card:#fff;--text:#241813;--muted:#705f58;--line:#eadbce;--brand:#d4500a;--danger:#c62828}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.6 Inter,system-ui,-apple-system,sans-serif}header{background:#fff;border-bottom:1px solid var(--line)}nav,main,footer{width:min(760px,calc(100% - 32px));margin:auto}nav{height:68px;display:flex;align-items:center;justify-content:space-between}.brand{font-size:22px;font-weight:800;color:var(--text);text-decoration:none}.links a{color:var(--muted);margin-left:18px}main{padding:44px 0 64px}h1{font-size:clamp(30px,7vw,44px);line-height:1.15;margin:0 0 12px}h2{font-size:20px;margin:32px 0 8px}p,li{color:var(--muted)}.lead{font-size:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:24px;margin-top:24px}label{display:block;font-weight:700;margin:14px 0 6px}input{width:100%;height:48px;border:1px solid #cdbdb2;border-radius:6px;padding:0 12px;font:inherit;background:#fff}button{width:100%;height:48px;border:0;border-radius:6px;margin-top:18px;background:var(--brand);color:#fff;font:700 15px inherit;cursor:pointer}button.danger{background:var(--danger)}button:disabled{opacity:.55;cursor:not-allowed}.notice{padding:12px;border-radius:6px;background:#f7eee6;color:var(--muted);margin-top:14px}.error{color:var(--danger)}.success{color:#087443}section[hidden]{display:none}footer{padding:24px 0;border-top:1px solid var(--line);color:var(--muted);font-size:13px}@media(max-width:520px){main{padding-top:28px}.links{font-size:13px}.card{padding:18px}}
</style></head><body><header><nav><a class="brand" href="/privacy">PullUp</a><div class="links"><a href="/privacy">Privacy</a><a href="/delete-account">Delete account</a></div></nav></header><main>${body}</main><footer>PullUp development team · Privacy contact: <a href="mailto:krish@pullupapp.in">krish@pullupapp.in</a></footer>${script ? `<script>${script}</script>` : ''}</body></html>`;

export const privacyPage = () => shell('Privacy Policy', `
<h1>Privacy Policy</h1><p class="lead">This policy explains how PullUp handles information when students use our carpooling and taxi-pooling services.</p><p><strong>Effective date:</strong> 25 August 2026</p>
<h2>Who operates PullUp</h2><p>PullUp is operated by the PullUp development team. Privacy questions and requests can be sent to <a href="mailto:krish@pullupapp.in">krish@pullupapp.in</a>.</p>
<h2>Information we collect</h2><p>We collect account and university identity information including university email, name, phone number, profile picture, course, division, role, and saved home address. Drivers may provide driving-licence images and verification status. We collect precise and background location when permitted for route matching, live rides, pickup, safety, and completion. We process ride, booking, fare, seat, cancellation, waitlist, live-location, chat, rating, notification, device push-token, subscription, payout, and transaction records.</p>
<h2>Camera and gallery</h2><p>Camera or gallery access is used only when you choose to upload a profile picture, driving licence, or chat image. Images are stored using Cloudinary. Device permissions can be changed in Android settings.</p>
<h2>Payments</h2><p>Razorpay processes checkout and payment details. PullUp receives order, payment, signature-verification, status, refund, transfer, and audit identifiers, but does not store complete card or bank credentials. Payment and wallet records may be retained where required for accounting, fraud prevention, disputes, and legal compliance.</p>
<h2>Services and sharing</h2><p>Firebase Authentication and Cloud Firestore provide authentication and application data storage. Firebase Cloud Messaging and Expo notification components support push delivery. Google Maps, Geocoding, and Routes services process locations to calculate road routes, distances, and fares. Cloudinary stores uploaded images. Razorpay processes payments and payouts. Relevant ride identity, pickup, and status details are shared with matched riders or drivers to provide the service. We do not sell personal information.</p>
<h2>How we use information</h2><p>We use information to authenticate users, complete profiles, verify drivers, create and match rides, calculate road-distance fares, process bookings and payments, enable chat and live tracking, send transactional notifications, prevent abuse, support users, diagnose failures, and meet legal obligations.</p>
<h2>Analytics and diagnostics</h2><p>The app and backend record operational logs, notification delivery metadata, route-cache data, audit events, and system statistics needed for reliability, security, and fraud investigation. Firebase configuration includes analytics capability; collection depends on the installed build and user/device settings.</p>
<h2>Security</h2><p>PullUp uses authenticated Firebase access, server-side privileged operations, encrypted network transport, restricted backend credentials, payment-signature verification, and rate limits. No system is risk free; report suspected misuse to the privacy contact above.</p>
<h2>Retention and deletion</h2><p>Account deletion removes the Firebase Authentication account, profile, personal contact data, push tokens, preferences, private notifications, and active participation where deletion is appropriate. Shared completed ride and payment/audit records may be retained in anonymized form when deleting them would affect another user, financial integrity, dispute handling, fraud prevention, or legal obligations. Cloudinary and service-provider backups may persist for their limited backup or legal retention periods before deletion. You can delete in Profile → Privacy & Account or use the public <a href="/delete-account">account deletion page</a>.</p>
<h2>Your choices and rights</h2><p>You may update profile data in the app, control camera, gallery, location, and notification permissions in device settings, request access or correction, or request account deletion. Contact <a href="mailto:krish@pullupapp.in">krish@pullupapp.in</a> for privacy requests that cannot be completed in the app.</p>
<h2>Children and campus eligibility</h2><p>PullUp is intended for eligible university users. Users must satisfy applicable age and university requirements.</p>
<h2>Policy updates</h2><p>We may update this policy as the service or legal requirements change. The effective date above will change, and material changes may also be communicated in the app.</p>`);

export const deleteAccountPage = () => shell('Delete Account', `
<h1>Delete your PullUp account</h1><p class="lead">You can permanently delete your account here even if the app is no longer installed.</p>
<div class="card"><p><strong>Deleting your PullUp account permanently removes your account and associated data. This action cannot be undone.</strong></p>
<section id="emailStep"><label for="email">University account email</label><input id="email" type="email" autocomplete="email" placeholder="you@university.edu"><button id="send">Send verification code</button></section>
<section id="otpStep" hidden><label for="otp">Verification code</label><input id="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6"><button id="verify">Verify code</button></section>
<section id="confirmStep" hidden><p class="notice">Active requests will be cancelled. Shared completed ride and financial records may be retained only in anonymized form where required.</p><label><input id="ack" type="checkbox" style="width:auto;height:auto"> I understand this action is permanent.</label><button class="danger" id="confirm" disabled>Permanently delete account</button></section>
<p id="message" role="status"></p></div>`, `
const byId=(id)=>document.getElementById(id);let deletionToken='';const message=byId('message');
const post=async(path,body)=>{const response=await fetch('/api/otp'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Request failed');return data};
byId('send').onclick=async()=>{message.textContent='';byId('send').disabled=true;try{await post('/account-deletion/send-otp',{email:byId('email').value});byId('emailStep').hidden=true;byId('otpStep').hidden=false;message.className='success';message.textContent='Check your email for the verification code.'}catch(e){message.className='error';message.textContent=e.message}finally{byId('send').disabled=false}};
byId('verify').onclick=async()=>{message.textContent='';byId('verify').disabled=true;try{const data=await post('/account-deletion/verify-otp',{email:byId('email').value,otp:byId('otp').value});deletionToken=data.deletionToken;byId('otpStep').hidden=true;byId('confirmStep').hidden=false;message.textContent=''}catch(e){message.className='error';message.textContent=e.message}finally{byId('verify').disabled=false}};
byId('ack').onchange=(event)=>byId('confirm').disabled=!event.target.checked;
byId('confirm').onclick=async()=>{byId('confirm').disabled=true;try{await post('/account-deletion/confirm',{deletionToken});byId('confirmStep').innerHTML='<h2>Account deleted</h2><p>Your PullUp account deletion is complete.</p>';message.textContent=''}catch(e){message.className='error';message.textContent=e.message;byId('confirm').disabled=false}};
`);